# Generated by Django 6.0.5 on 2026-05-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedocument',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
